# Generated by Django 3.2.13 on 2022-11-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='userregistrationmodel',
            table=None,
        ),
        migrations.CreateModel(
            name='UserAdd_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('records', models.CharField(max_length=1000)),
                ('organizationtype', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=100)),
                ('adddata', models.CharField(max_length=500)),
                ('attackresult', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=100)),
                ('uregid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistrationmodel')),
            ],
            options={
                'db_table': 'UserRegistrations',
            },
        ),
    ]
